name: Latest book list from goodreads
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update-readme-with-goodreads-books:
    name: Update this repo's README with what you're currently reading
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zwacky/goodreads-profile-workflow@v1.2.4
        with:
          goodreads_user_id: "12291100"
          shelf: "currently-reading"
          template: "- [$title]($url) by $author"
      - uses: zwacky/goodreads-profile-workflow@v1.2.4
        with:
          goodreads_user_id: "12291100"
          shelf: "read"
          comment_tag_name: "GOODREADS-LIST-READ"
          max_books_count: "5"
          template: "- [$title]($url) by $author"
